# Generated by Django 3.1.5 on 2021-01-22 11:07

from django.db import migrations, models
import membership.models


class Migration(migrations.Migration):

    dependencies = [("membership", "0004_member_is_active")]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="picture",
            field=models.ImageField(max_length=250, upload_to=membership.models.upload_path),
        )
    ]
