# Generated by Django 3.1.5 on 2021-01-22 17:04

from django.db import migrations, models
import membership.models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_auto_20210122_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='picture',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to=membership.models.upload_path),
        ),
    ]
